dlme_airflow/dags/aims_harvester.py
dlme_airflow/dags/aub_harvester.py
dlme_airflow/harvester/aims.py
dlme_airflow/harvester/aub.py
dlme_airflow/harvester/copydir.py
requirements.txt
setup.cfg

Fixes #9
Adds [flake8](https://flake8.pycqa.org/en/latest/index.html) linter to project. Also adds [black](https://black.readthedocs.io/en/stable/index.html) code formatter to make it easier to pass the linter!

Adds flake8 and black

---

README.md

Fixes #13
Directions for creating a virtual environment, installing dependencies, and then running flake8 and black to README.

README Dev updates.

---

.circleci/config.yml

Adds Circle-CI 

---

.circleci/config.yml

Adds deployment to circle build configuration

Add ecs update to circle deployment

---

catalogs/aub.yaml
catalogs/catalog.yaml
dlme_airflow/dags/harvest_aub.py
dlme_airflow/drivers/oai_xml.py
dlme_airflow/utils/catalog.py
docker-compose.yaml

This adds the OAI based xml partner driver to our intake architecture.

Add OAI Intake driver

---

.circleci/config.yml

Update circle image to move away from legacy container image

---

catalogs/aims.yaml
catalogs/ans.yaml
catalogs/catalog.yaml
catalogs/harvard.yaml
catalogs/manchester.yaml
catalogs/texas_tech.yaml
dlme_airflow/utils/dataframe.py

Adds collections that have no pre or post harvest steps.

adds easiest collections

---

Dockerfile

Update to the latest airflow version and python update

---

dlme_airflow/dags/harvest_catalog.py
dlme_airflow/drivers/iiif_json.py
dlme_airflow/drivers/oai_xml.py
dlme_airflow/drivers/xml.py
dlme_airflow/harvester/source_harvester.py
dlme_airflow/harvester/source_post_harvester.py
dlme_airflow/services/harvest_dag_generator.py
dlme_airflow/task_groups/detect_metadata_changes.py
dlme_airflow/task_groups/etl.py
dlme_airflow/task_groups/index.py
dlme_airflow/task_groups/validate_dlme_metadata.py
dlme_airflow/tasks/check_equality.py
dlme_airflow/tasks/harvest.py
dlme_airflow/tasks/harvest_report.py
dlme_airflow/tasks/index.py
dlme_airflow/tasks/post_harvest.py
dlme_airflow/tasks/send_harvest_report.py
dlme_airflow/tasks/transform.py
dlme_airflow/utils/catalog.py
dlme_airflow/utils/dataframe.py
dlme_airflow/utils/driver_tag.py
dlme_airflow/utils/ifpo_get_thumbnail_urls.py
dlme_airflow/utils/yale_babylon_remove_non_relevant_records.py
requirements.txt
setup.cfg

This is all just linting corrections:
- first ran black to autocorrect as much as possible (mostly single to double quotes, etc)
- removed unused includes
- `noqa` marked areas to pass thinking but should be revisited for refactoring

Fix linting errors

---

Dockerfile

Update to airflow 2.3.3

---

README.md
dlme_airflow/task_groups/index.py
dlme_airflow/tasks/index.py
dlme_airflow/tasks/transform.py
docker-compose.yaml

This removes hard coded AWS specific values. While the particular values should not present any security risk we should avoid these values in code when possible.

Move AWS specific settings into ENV vars

---

README.md

Since a poetry configuration is provided I think it makes sense to use
it when installing locally.
Also the iiif example was moved into the iiif section.

Poetry instructions

---

dlme_airflow/task_groups/etl.py
dlme_airflow/tasks/harvest.py

fix typo in method name

---

catalogs/aims.yaml
catalogs/ans.yaml
catalogs/aub.yaml
catalogs/auc.yaml
catalogs/bodleian.yaml
catalogs/cambridge.yaml
catalogs/csic.yaml
catalogs/dasi.yaml
catalogs/harvard.yaml
catalogs/ifpo.yaml
catalogs/manchester.yaml
catalogs/penn.yaml
catalogs/princeton.yaml
catalogs/qnl.yaml
catalogs/sakip_sabanci.yaml
catalogs/stanford.yaml
catalogs/texas_tech.yaml
catalogs/yale.yaml

Part of #155, in large part this will fix existing issues fetching the appropriate metadata (especially for reporting).
A follow up PR may be coming to add missing collections, so I will keep 155 open until analysis is complete.

Refresh existing collection data_path values to match dlme-transform

---

dlme_airflow/drivers/iiif_json.py

The IIIF driver can sometimes generate CSV rows that contain no values:
```
$ grep ,,,,, metadata/auc/postcards/data.csv
,,,,,,,,,,,,,,,,,,
```
This change will prevent those from getting generated by looking for manifests that lack any values in their corresponding metadata dictionary. If they are found an empty DataFrame is returned instead, which can be safely concatenated with all the others.
Closes #192

Prevent empty CSV rows

---

dlme_airflow/drivers/iiif_json.py
tests/drivers/test_iiif_json.py

the first commit captures the current behavior in a test.
the second commit is my attempt at fixing what appears to be an unreachable codepath.  discussed with @aaron-collier after standup, and we both thought the change in this PR fixed the code to do what was actually intended.  stumbled on that when looking at lines that were uncovered among the driver modules, according to the coverage report.
the other commits add test coverage and do some minor renaming/commenting/refactoring, for better consistency/clarity (hopefully).
closes #169

more intake driver test coverage, pt2

---

README.md

* clean up heading titles and indentation
* add info on type checking, and some other random development tooling tips

Readme touchups

---

dlme_airflow/drivers/iiif_json.py

see https://github.com/sul-dlss/dlme-airflow/pull/218#discussion_r967370698

take suggested simplification from prior PR review

---

docker-compose.yaml

This sets a few configuration options through the docker compose ENV, mostly timezone and worker concurrency. The other changes are just reordering.

Set config values through env

---

catalogs/ans.yaml
catalogs/aub.yaml
catalogs/auc.yaml
catalogs/bnf.yaml
catalogs/bodleian.yaml
catalogs/cambridge.yaml
catalogs/csic.yaml
catalogs/dasi.yaml
catalogs/harvard.yaml
catalogs/ifpo.yaml
catalogs/manchester.yaml
catalogs/penn.yaml
catalogs/princeton.yaml
catalogs/qnl.yaml
catalogs/sakip_sabanci.yaml
catalogs/shahre_farang.yaml
catalogs/stanford.yaml
catalogs/texas_tech.yaml
catalogs/yale.yaml

This is to test daily runs in AWS where the start time is offset by 20 minutes for each provider. This should limit the overlap and avoid out-of-memory/cpu crashes in the worker.

Offset provider runs by 20 minutes starting at midnight

---

catalogs/aub.yaml
catalogs/manchester.yaml
catalogs/texas_tech.yaml
catalogs/yale.yaml

This fixes a few minor config issues that will be caught by future schema validation.

Fix catalogs to follow future schema

---

catalogs/yale.yaml
dlme_airflow/tasks/post_harvest.py
dlme_airflow/utils/yale.py

Good eye @jmartin-sul , fixed up here.

Fix path to yale babylonian

---

dlme_airflow/tasks/send_harvest_report.py

I'm currently the only one receiving the harvest report emails. This utilizes the listserv which will go to me and @jacobthill at this time.

Use new dlme-monitoring listserv for harvest report

---

catalogs/qnl.yaml
dlme_airflow/utils/qnl.py

Small bug fix for QNL to update to the proper data_path and the path to the working csv for post harvest.

Update QNL data_path and post harvest path

---

catalogs/bodleian.yaml

Fixes a file path to Bodleian traject config

Etl cleanup

---

dlme_airflow/tasks/harvest_report.py

Makes language value counts an average.

fix lang counts

---

catalogs/auc.yaml
catalogs/catalog.yaml
catalogs/lebanese_american_university.yaml
catalogs/princeton.yaml

- Adds new Lebanese American University collections
- Adds new Princeton collection
- Fixes some file path issues with AUC

New collections

---

dlme_airflow/tasks/harvest_report.py

Round language count averages to 2 places

round language count averages, fixes #319

---

catalogs/aims.yaml
catalogs/american_numismatic_society.yaml
catalogs/aub.yaml
catalogs/auc.yaml
catalogs/bnf.yaml
catalogs/bodleian.yaml
catalogs/cambridge.yaml
catalogs/csic.yaml
catalogs/dasi.yaml
catalogs/harvard.yaml
catalogs/ifpo.yaml
catalogs/lebanese_american_university.yaml
catalogs/manchester.yaml
catalogs/penn.yaml
catalogs/princeton.yaml
catalogs/qnl.yaml
catalogs/sakip_sabanci_museum.yaml
catalogs/shahre_farang.yaml
catalogs/texas_tech.yaml
catalogs/yale.yaml

schedule DAGs

---

dlme_airflow/tasks/transform.py
dlme_airflow/utils/dataframe.py
docker-compose.prod.yaml
docker-compose.yaml
poetry.lock
pyproject.toml

Verified this work against local storage and the shared mount for ndjson sharing. 
This shifts from an ECS operator to a local DockerOperator.

User DockerOperator for transform task

---

dlme_airflow/tasks/index.py
tests/tasks/test_index.py

Return the serialized response from the index task

---

dlme_airflow/tasks/transform_validation.py
docker-compose.prod.yaml
docker-compose.yaml
tests/tasks/test_transform_validation.py

This updates to use the correct transform image and updates where validation looks for the ndjson file

Small fixes for on prem deployment for transform image

---

catalogs/aims.yaml

The query for the aims thumbnail changed

---

.gitignore
dlme_airflow/models/collection.py
dlme_airflow/tasks/archive.py
dlme_airflow/utils/dataframe.py
docker-compose.prod.yaml
docker-compose.yaml
tests/tasks/test_archive.py

Introduce an ARCHIVE_PATH environment variable that defines where the archived harvest data is written to.
Fixes #383

ARCHIVE_PATH

---

bin/get
dlme_airflow/utils/qnl.py

Currently seeing some strange output with this:
The index is getting split up into individual characters.
```
{"id":["8","1","0","5","5","\/","v","d","c","_","1","0","0","0","2","3","5","5","7","3","5","3",".","0","x","0","0","0","0","0","1","_","a","r","8","1","0","5","5","\/","v","d","c","_","1","0","0","0","2","3","5","5","7","3","5","3",".","0","x","0","0","0","0","0","1","_","e","n"],"author":["سرحان بن سعيد بن سرحان","تشارلز ميتكالف ماكريجور","إدوارد تشارلز روس","Sirhān bin Sa‘īd-bin Sirhān","Charles Metcalfe MacGregor","Sir Edward Charles Ross, Knight"],"shown_at":["http:\/\/www.qdl.qa\/%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9\/archive\/81055\/vdc_100023557353.0x000001","http:\/\/www.qdl.qa\/en\/archive\/81055\/vdc_100023557353.0x000001"],"preview":["https:\/\/images.qdl.qa\/iiif\ …
```

Update QNL post-harvest for JSON format

---

.autoupdate/preupdate

Fixes #398 
This is part of weekly dependency updates that we run in Jenkins.

Add pre-update script to bump Python dependencies

---

docker-compose.prod.yaml

Update indexing endpoint to review server

---

docker-compose.prod.yaml
docker-compose.yaml

This turns the harvest reporting step back on.

Enable harvest reporting step

---

docker-compose.prod.yaml

Use correct indexing endpoint

---

dlme_airflow/tasks/mapping_report.py
docker-compose.prod.yaml
docker-compose.yaml
tests/conftest.py
tests/tasks/test_harvest_report.py

This fixes a mismatch in the docker local path and the host local path to the data file for reporting.

Use the proper IR path in the harvest report

---

catalogs/princeton.yaml

Switched Princeton to json harvesting and mapping

switch Princeton to json

---

Dockerfile
docker-compose.yaml
poetry.lock
pyproject.toml

This updates airflow, python, and poetry - it quiets most of the deprecation warnings on startup, etc.

Update python, airflow, and poetry

---

README.md
bin/get
catalogs/catalog.yaml
catalogs/ucla.yaml
dlme_airflow/drivers/iiif_json.py
tests/drivers/test_iiif_json.py

- Adds new UCLA collections
- Makes iiif_json driver compliant with IIIF v3 object naming rules
- makes json the default output of bin/get

Add ucla collections, update iiif_json driver and bin/get

---

catalogs/catalog.yaml
catalogs/newcastle.yaml

add newcastle catalog

---

tests/data/json/116787.json
tests/data/json/60732.json
tests/data/json/incremental_paging.json
tests/data/json/pre_fetch_ids.json
tests/drivers/test_json.py
tests/utils/test_partition_url_builder.py

Improving test coverage to wrap up this phase of JSON work.

Improve test coverage of the PartitionBuilder

---

dlme_airflow/utils/partition_url_builder.py
tests/utils/test_partition_url_builder.py

Small bug fix for LOC paged harvesting

Fix bug when extracting page URLs for LOC

---

Gemfile.lock

Just adds the new M3 chip based platform like to Gemfile.lock

Update lock platforms for new laptops

---

compose.prod.yaml
compose.yaml
config/deploy.rb

See: https://docs.docker.com/compose/compose-application-model/#the-compose-file

Update docker-compose config naming

---

catalogs/aub.yaml
catalogs/auc.yaml
catalogs/csic.yaml
catalogs/dasi.yaml
catalogs/harvard.yaml
catalogs/ifpo.yaml
catalogs/manchester.yaml
catalogs/qalamos.yaml
catalogs/qnl.yaml
catalogs/texas_tech.yaml
catalogs/ucla.yaml

This makes `full_harvest` and `allow_expiration` explicit in the catalog so we don't forget again that we have that option.

Catalog changes for oai_xml collections

---

Gemfile.lock

Just adding this line so it doesn't trip anyone up.

Add platform for updated macos

---

catalogs/auc.yaml

Add new AUC collections

---

dlme_airflow/drivers/iiif_json_v3.py

There can be missing `value` components for metadata values, skip those.

Fix bug with missing values

---

catalogs/michigan.yaml

Adds the Michigan Islamic Manuscripts collection using the hathi driver

---

bin/validate-traject
catalogs/sakip_sabanci_museum.yaml

This utility is proving very useful for local transform. I opened a ticket to eventually move this logic to the transform-validation task.

revise bin/validate-traject

---

catalogs/loc.yaml

This adds the WDL collection but it is failing the filter task. Opening a new ticket for that.

adds WDL collection

---

dlme_airflow/drivers/iiif_json.py
tests/drivers/test_iiif_json.py

Language tag label value with _lang key if present.

---

dlme_airflow/drivers/hathi_trust.py

Flatten fields from marc records in json

---

catalogs/harvard.yaml
dlme_airflow/drivers/xml.py
tests/data/xml/paged/pagination_1.xml
tests/data/xml/paged/pagination_2.xml
tests/drivers/test_xml.py

Implement parsing of pagination provided in XML results as pagination

---

catalogs/harvard.yaml

Update Harvard SCW configuration for proper ID in dataframe

---

catalogs/openn.yaml

Add required ID to OPenn configuration

---

dlme_airflow/drivers/xml.py

Force utf-8 encoding of response text to resolve odd characters

---

dlme_airflow/drivers/iiif_json.py

Ignore provider specific metadata in IIIF that doesn't match the spec

---

dlme_airflow/drivers/hathi_trust.py

Flatten marc output in Hathi driver as field_subfield

---

README.md

Updates the readme badge to CodeCov

Add Codecov badge to readme

---

.autoupdate/preupdate
README.md

Switch from poetry to uv for Python dep updates

---

.autoupdate/preupdate

We just need to ensure we've got the latest uv installed and let it take it from there.

Align dep updates
