sul-dlss/dlme-airflow

- README.md
- requirements.txt
- tests/harvester/test_copydir.py
Fixes #10 
Created an example unit test for the `copydir` module using [pytest][PYTEST] mocking and using a temporary path. 
Updated README with directions on using [pytest][PYTEST].
[PYTEST]: https://docs.pytest.org/en/6.2.x/
> Adds pytest with example test

- Dockerfile
This install git into the docker image so that it is available within Airflow and BashOperators. This will be necessary for cloning metadata and pushing changes.
> Add git to the docker image so it is available to the BashOperator

- Dockerfile
- catalog.yaml
- dlme_airflow/dags/intake_harvester.py
- dlme_airflow/harvester/aims.py
- dlme_airflow/harvester/csv.py
- docker-compose.yaml
- requirements.txt
- tests/harvester/test_csv.py
Fixes #2 
WIP PR uses [Intake](https://intake.readthedocs.io/en/latest/index.html) to configure three csv data-sources `ans`, `penn_egyptian_museum`, and `yale_babylonian` in a catalog.yml. Not sure we actually need a separate csv_harvester function as I think we can directly call the Intake catalog from the respective dags but leaving the function and tests for now. 
Includes new `intake_harvester` DAG that requires a provider configuration to be set per run in Airflow. I think in a follow-up we may have a list of providers or other way to do this harvesting and validation.
> Initial CSV Harvester 

- dlme_airflow/drivers/iiif_json.py
Adds `_get_partition` method to fix this log error (adds some missing type hints as well):
```
[2021-08-27 17:22:43,146] {source_harvester.py:41} INFO - Starting harvest of bodleian
[2021-08-27 17:22:43,155] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
self._prepare_and_execute_task_with_callbacks(context, task)
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
result = self._execute_task(context, task_copy)
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
result = …
```
> Implements _get_partition method in IIIF JSON Harvester

- Dockerfile
- catalogs/catalog.yaml
- dlme_airflow/harvester/source_harvester.py
- docker-compose.yaml
This is a small change to docker-compose to allow for reloading of the dags and harvest code without rebuilding the container and restarting docker compose.
> Mount DAGS and catalogs to avoid building during development

- catalogs/catalog.yaml
- dlme_airflow/dags/harvest_catalog.py
- dlme_airflow/drivers/xml.py
This adds a generic and configurable xml driver and the AIMS collection as a patter for configuring XML based collections.
Output can be viewed here: https://github.com/sul-dlss/dlme-metadata/blob/intake/aims/data.csv/data.csv
> Add Generic XML Intake driver and setup AIMS as first xml based provider

- catalogs/aub.yaml
- catalogs/auc_iiif.yaml
- catalogs/bodleian.yaml
- catalogs/catalog.yaml
- catalogs/penn_museum.yaml
- dlme_airflow/harvester/source_harvester.py
- dlme_airflow/tasks/check_equality.py
- dlme_airflow/utils/dataframe.py
- dlme_airflow/utils/yale_babylon_remove_non_relevant_records.py
This addresses inconsistencies when configuring the existing and working metadata paths in the catalog.yaml configuration.
> Refactor to use data_path (with a default) to avoid errors in the catalog config.

- catalogs/ifpo.yaml
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/post_harvest.py
- dlme_airflow/utils/ifpo_get_thumbnail_urls.py
@jacobthill Feel free to close this PR if you'd like to incorporate these suggestions into your branch (i.e. take this as an example or we can pair to walk through getting it running).
Essentially this moves the post_harvest config param into metadata for more reliable fetching than at the root level. Then instead of a file path to a script, it's a simple method name. That method should be included in the post_harvest_task so that `run_post_harvest` can call it from globals.
Let's chat on monday if we'd like to work on this further.
> Establish a pattern for dynamic post harvest scripts

- dlme_airflow/task_groups/etl.py
- dlme_airflow/task_groups/validate_dlme_metadata.py
Injecting the source catalog is required to use the `data_path` configuration setting per collection when syncing metadata to s3.
Fixes #97 
Fixes #151
> Add source catalog to build sync metadata task group

- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/harvest_report.py
- dlme_airflow/tasks/transform.py
Resolves inconsistency between collection naming and the data path used for the intermediate representation from dlme-transform.
This is a precursor to refactoring the harvest report.
> Update harvest and transform tasks for proper data_path

- docker-compose.yaml
This allows local development to avoid needed to docker build and restart the stack for most code changes while actively in development.
> Add dlme_airflow volume in docker compose

- README.md
The docker-compose.yml expects to find `AWS_ACCESS_KEY` instead of `AWS_ACCESS_KEY_ID` from the `.env` file.
> Fix AWS access key env var

- README.md
- dlme_airflow/task_groups/etl.py
- docker-compose.yaml
If SKIP_REPORT is defined in the environment don't generate and send the report. This is for development environments that are using the `.env` file.
Closes #161
> SKIP_REPORT

- dlme_airflow/services/harvest_dag_generator.py
- dlme_airflow/task_groups/validate_dlme_metadata.py
Closes #179 
This removes the first task of current DAGs that downloads the existing metadata from S3. This is unused data at this time and may be moved to a task after harvesting later.
> Remove sync metadata task group - unused

- catalogs/penn.yaml
- catalogs/yale.yaml
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/post_harvest.py
- dlme_airflow/utils/add_thumbnails.py
- dlme_airflow/utils/schema.py
- dlme_airflow/utils/yale_babylon_remove_non_relevant_records.py
- docker-compose.yaml
- poetry.lock
- pyproject.toml
- tests/utils/test_schema.py
Add a new add_thumbnails post-harvest task for Penn museums. It currently depends on extracting thumbnailURL from schema.org JSON-LD metadata that is embedded in the item's webpage. The thumbnail URL is then persisted to the harvest CSV as a new column `thumbnail`.
This should work for any provider that embeds JSON-LD in their item pages. 
**WARNING: this post harvest task will generate 100k requests to the [www.penn.museum](https://www.penn.museum/) website when run for the Penn workflow.**
closes #158
> post-harvest task for thumbnails

- catalogs/yale.yaml
- dlme_airflow/dags/harvest_catalog.py
- dlme_airflow/drivers/sequential_csv.py
- dlme_airflow/utils/dataframe.py
- tests/data/csv/example1.csv
- tests/data/csv/example2.csv
- tests/data/csv/example3.csv
- tests/data/csv/example4.csv
- tests/data/csv/example5.csv
- tests/drivers/test_sequential_csv.py
SequentialCsvSource loads CSVs sequentially using pandas rather than using dask which issues HEAD requests in parallel to get the content-length and see if the server supports HTTP Range requests. Since `collections.peabody.yale.edu` is dynamically generating the CSV responses it is getting 20 concurrent HEAD requests which seems to cause it to throw a 500 Internal Server Error. Loading each CSV one at a time, and merging in to a single DataFrame for further processing seems to not cause the server errors.
While this closes #152 since the harvest works I don't think the downstream transform task is working?
> SequentialCsvSource

- README.md
- catalogs/catalog.yaml
- dlme_airflow/dags/harvest_catalog.py
- dlme_airflow/drivers/iiif_json.py
- dlme_airflow/drivers/oai_xml.py
- tests/drivers/test_iiif_json.py
The driver classes have abbreviations in them. This commit changes them to use CamelCase for consistency. So IiifJsonSource instead of IIIFJsonSource or IIIFJSONSource, and OaiXmlSource instead of OAIXmlSource.
Fixes #186
> Normalize abbreviations in class names

- .circleci/config.yml
- catalogs/catalog.yaml
- dlme_airflow/dags/harvest_catalog.py
- dlme_airflow/services/harvest_dag_generator.py
- poetry.lock
- pyproject.toml
- tests/services/test_harvest_dag_generator.py
closes #168
* test the DAGs we build for cycles
* refactor a bit to make that testing easier
* switch to relative paths for the inclusions in `catalog.yml`, so that the tests don't depend on a hardcoded path when loading the catalog
* give the test suite a `PYTHONPATH` so it can find our modules
* update black so that it specifies a compatible version of click
note: if you glance at the test coverage, it seems total coverage has dropped, but that's just because more files are being counted in the coverage report.
[before](https://app.circleci.com/pipelines/github/sul-dlss/dlme-airflow/381/workflows/17166a18-04c1-43e8-b8d9-beb9b6cf2420/jobs/693?invite=true#step-110-15):
```
---------- coverage: platform linux, python 3.9.13-final-0 -----------
Name …
```
> check DAGs for cycles

- catalogs/ans.yaml
This restores the dtype definition for ANS, this is required for the metadata to properly be ingested into a pandas dataframe.
> Restore dtype specification for ans

- dlme_airflow/dags/harvest_catalog.py
- dlme_airflow/services/harvest_dag_generator.py
*This is an alternative approach to making DAGs discoverable without rolling back changes made in #195.*
---
Airflow has an amusing heuristic to determine whether a folder contains dags or not:
https://github.com/apache/airflow/blob/main/airflow/utils/file.py#L337-L357
Basically the .py file must contain the words 'airflow' and 'dag' and since dlme_airflow.dags.harvest_catalog.py no longer does it isn't loading it at all :)
The other problem is that the DAG classes are being created in the dlme_airflow.services.harvest_dag_generator module instead of dlme_airflow.dags.harvest_catalog. So even after aiflow has loaded the file it doesn't find any DAG classes in it, and so it decides there aren't any.
So this commit adds a comment with 'airflow' and 'dag' in it to …
> Ensure DAGs are defined in harvest_catalog module (alt)

- dlme_airflow/drivers/oai_xml.py
If an element lacks text it could cause an exception during havest when trying to strip the text.
This also adjusts the child traversing logic to always run when there are child elements.
Closes #216
> Guard against el.text being None

- catalogs/aims.yaml
- dlme_airflow/services/harvest_dag_generator.py
- docker-compose.yaml
This introduces the ability to set the DAG schedule in the catalog per provider.
- Adds `schedule` to the provider catalog metadata
- Looks for an `DEFAULT_DAG_SCHEDULE` environment variable set in docker compose or terraform for deployment
- If the `DEFAULT_DAG_SCHEDULE` is missing, defaults to `@daily`
With one collection configured in the catalog and the remainder set by `DEFAULT_DAG_SCHEDULE`:
With one collection configured in the catalog and the remainder set to `@daily` due to missing `DEFAULT_DAG_SCHEDULE`:
> Add schedule config option to catalog with @daily default

- dlme_airflow/drivers/iiif_json.py
- tests/drivers/test_iiif_json.py
not sure if a list type for a single field value would be valid IIIF, but i ran into this test case when i was trying to cover some of the code paths that were being missed on the iiif_json.py driver (see #214), before i better understood what slightly simpler manifest structure would hit those paths.
we can close this if we never expect to run into data like this, or if this would hide some other problem, or otherwise result in undesired data transformation.
connects with #169
> iiif_json.py: more robust handling of non-string types for specified fields

- catalogs/ans.yaml
Very small PR to add these field DTypes that are causing ANS to fail.
```
ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.
+----------------+--------+----------+
| Column         | Found  | Expected |
+----------------+--------+----------+
| Reverse Legend | object | float64  |
| Reverse Type   | object | float64  |
+----------------+--------+----------+
The following columns also raised exceptions on conversion:
- Reverse Legend
ValueError("could not convert string to float: 'MRA in circle | bismillah zhal-fals | biHalab waf'")
- Reverse Type
ValueError("could not convert string to float: 'crescent with three stars, scroll, value'")
Usually this is due to dask's dtype inference failing, and
*may* be fixed by specifying dtypes manually by adding:
dtype={'Reverse …
```
> Add missing fields that cause ANS to fail harvest

- Dockerfile
- poetry.lock
- pyproject.toml
This commit speeds up the Docker build by pinning the httpx dependency. I noticed that Docker was having to dowload different versions of httpx as part of its dependency management:
https://pip.pypa.io/en/stable/topics/dependency-resolution/#possible-ways-to-reduce-backtracking
I only noticed this URL in a warning once I had upgrade poetry to v1.2.0. I also ran poetry update to get the latest dependencies which is why the poetry.lock file is so different.
Maybe more tweaks can be made, but just addressing httpx is a significant improvement:
```
before: 06:23.23
after:  00:48.840
```
Closes #211
> Pin httpx to speed up docker build

- catalogs/auc.yaml
- dlme_airflow/models/provider.py
- dlme_airflow/services/harvest_dag_generator.py
- dlme_airflow/task_groups/etl.py
- dlme_airflow/task_groups/validate_dlme_metadata.py
- dlme_airflow/tasks/post_harvest.py
- tests/services/test_harvest_dag_generator.py
Adds the Provider intake configuration option `separate_dags` which when it is set to `true` will cause the collections to run as individual DAGS rather than as TaskGroup which parallelizes them all. This will allow for separate scheduling of the individual DAGs to avoid situations where many concurrent requests are being made to the same Provider server.
Closes #131
> Separate DAGS

- catalogs/bnf.yaml
The srw namespace config field is configured under `path` but needs to be under `namespace`
> Fix order of config for BNF

- docker-compose.yaml
This allows us to avoid manually setting the connection configuration up for local development through docker compose using local env vars to avoid sharing authentication information.
Confirmed this works locally.
> Use the env in order to establish an aws connection

- .codeclimate.yml
This excludes `catalogs/` from coverage calculations. `tests/` is covered by default, however, with this file established we have to declare it as well.
> Do not include catalogs in coverage calculations

- bin/get
- catalogs/qnl.yaml
- dlme_airflow/drivers/oai_xml.py
- tests/drivers/test_oai_xml.py
This adds a wait option for the OaiXmlSource driver which will inject a sleep of n seconds between sending HTTP requests to the OAI server.
Sickle allows you to pass in your own iterator class, which gets used internally when making requests. This class needs to change its behavior depending on the desired wait time, so it is created dynamically by the make_iterator() function.
The QNL intake catalog entry has been adjusted to use `wait: 2` which fixes #200.
I also added a `--log` option to bin/get to write the sleep messages (and other diagnostics) to a file.
Closes #235
> Implement wait option for OaiXmlSource

- dlme_airflow/models/collection.py
- dlme_airflow/models/provider.py
- docker-compose.yaml
- tests/models/test_collection.py
- tests/models/test_provider.py
This follows a comment by @edsu when establishing these models to move the catalog methods into decorated properties to allow for instantiation of mocks for easier use in testing.
> Refactor models for easier testing instantiation

- .circleci/config.yml
Looks like the 2.0.3 orb is no longer valid, 2.1.1 was updated a few days ago.
> Update the circleci python orb

- dlme_airflow/models/collection.py
- dlme_airflow/models/provider.py
In 38df69fcbb5bfc2e33375db3babb723ffe478840 we stopped instantiating one catalog per Collection and Provider in the constructor and instantiate a new one each time the `catalog` property is used. This means that you can't actually modify the one that will get used by intake. This isn't usually an issue except for the `bin/get` utility with tries to set `.record_limit` after the fact, but prior to running the harvest.
> Fix bin/get --limit

- bin/get
- dlme_airflow/drivers/xml.py
- tests/data/xml/multi.xml
- tests/drivers/test_xml.py
This is a significant refactor of the XmlSource driver so that it handles multiple field values correctly. Previously it was only recording the first example, instead of creating a list. In addition there was a bug that was causing multiple duplicate rows to be returned, which was caused by the `npartitions` logic used by intake. There is only one partition for the data since it is a single XML document that is read in and processed.
The test for XmlSource was simplified to use requests_mock, and also to look for values in the resulting DataFrame rather than comparing DataFrames.
The desired behavior is for XML like:
```xml
<records>
<record>
<id>1</id>
<title>Article 1</title>
<name>Donna Haraway</name>
<name>bell hooks</name>
</record>
<record>
<id>2</id>
<title>Article 2</title> …
```
> Handle multiple fields in XmlSource driver

- dlme_airflow/drivers/iiif_json.py
- tests/drivers/test_iiif_json.py
The princeton/manuscripts harvest was failing because one of the manifest URLs was a 404. This change adds a skip behavior for any manifests that don't return a 200 OK. Any manifests that fail to load are logged:
```
2022-09-21 15:36:21,552 - ERROR - got 404 when fetching manifest https://figgy.princeton.edu/concern/scanned_resources/e6977a4b-edd4-4aa6-bcb0-c605a82d2721/manifest
```
Closes #251
> Handle 404 errors in IiifJsonSource

- README.md
- docker-compose.yaml
Adding an environment variable for situations where the secret key needs to be url-encoded.
> URL encode AWS_SECRET_ACCESS_KEY for aws_conn

- catalogs/auc.yaml
The data_path should be `oai` instead of `iiif` for the campus_photos collection in order to properly transform the data (the configuration uses is based on this path: https://github.com/sul-dlss/dlme-transform/blob/main/config/metadata_mapping.json#L223)
> AUB Campus Photos uses the OAI driver

- tests/catalogs/test_catalogs.py
- tests/support/schemas/schema.yaml
Some questions on this draft PR: 
1. I think we can just use one schema for all the catalogs (see the `allOf` section that has some logic based on the driver). Where should the `schema.yaml` best live?
2. What are the other validations we want to add?
3. We can add description of each field, but I don't know enough yet about the fields to provide those.
> Setting up catalog validation

- README.md
- poetry.lock
- pyproject.toml
Since our existing dev-dependencies configuration is [deprecated with poetry 1.2](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups), use a dev group in pyproject.toml. Also updates the installation instructions to no longer use pip.
> Use poetry 1.2 groups

- .codeclimate.yml
- dlme_airflow/harvester/source_harvester.py
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/harvest_validator.py
- dlme_airflow/utils/dataframe.py
- docker-compose.yaml
- tests/tasks/test_harvest_validator.py
- tests/utils/test_dataframe.py
Closes #209 
This adds a validation task that compares the current and prior harvest. Ending the pipeline if the data has not changed.
If there are no differences between the current and previous harvest, the ETL pipeline will be skipped:
If any differences are detected the ETL pipeline will be started:
Note: this adds a SKIP_HARVEST_VALIDATION env var to docker compose to avoid including this step during local development. At this time, this interacts directly with S3, so only has access to the S3 bucket when deployed to AWS.
> Establish data flow with harvest validation

- catalogs/american_numismatic_society.yaml
- dlme_airflow/task_groups/validate_dlme_metadata.py
A couple of small bug fixes.
- We need the same `S3_BUCKET` values in datafrom_from_s3 and `sync_data` however the former can't have the `s3://` prefix while the latter needs it.
- Sets the data path on ANS to fix the main build.
Verified locally this fixes the `assume_role` failure.
> Fix s3 and catalog bug

- dlme_airflow/services/harvest_dag_generator.py
This moves catchup=False from the default_args for the Operator to the DAG itself.
Closes #289
> Assign catchup on the DAG

- .circleci/config.yml
- .yamllint.yaml
- README.md
- catalogs/aub.yaml
- catalogs/csic.yaml
- catalogs/dasi.yaml
- catalogs/harvard.yaml
- catalogs/ifpo.yaml
- catalogs/manchester.yaml
- catalogs/qnl.yaml
- catalogs/texas_tech.yaml
- poetry.lock
- pyproject.toml
* add YAML linting for Intake catalog configs
* normalize catalog configs on `true` and `false` for boolean values (gets rid of warnings from yamllint for the [`truthy`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy) rule)
* if you look at the CircleCI logs for the first commit, you can see [an example of yamllint's warnings in CI](https://app.circleci.com/pipelines/github/sul-dlss/dlme-airflow/674/workflows/9a913c30-4cbc-4fc1-9f65-a771574b5101/jobs/1801?invite=true#step-113-4)
connects with #132
> catalog config yaml linting

- catalogs/cambridge.yaml
I'm not sure that the thumbnails are available via these manifiests, but here is a configuration to get the first JP2.
```
bin/get cambridge genizah --limit 5 | xsv select thumbnail
thumbnail
https://images.lib.cam.ac.uk/iiif/MS-ADD-02586-000-00001.jp2
https://images.lib.cam.ac.uk/iiif/MS-ADD-03335-000-00001.jp2
https://images.lib.cam.ac.uk/iiif/MS-ADD-03336-000-00001.jp2
https://images.lib.cam.ac.uk/iiif/MS-ADD-03337-000-00001.jp2
https://images.lib.cam.ac.uk/iiif/MS-ADD-03340-000-00001.jp2
```
Closes #288
> Add Cambridge images

- dlme_airflow/drivers/iiif_json.py
Fixes #283 
Princeton is providing language tagged IIIF, something like:
```
"metadata": [
{
"label": "Director",
"value": [
{
"@language": "ara-arab",
"@value": "محمود فريد"
}
]
},
{
"label": "Date Created",
"value": [
"1974"
]
}
]
```
Notice the first `value` is a hash with `@language` and `@value`, and the second entry the `value` is a simple string. Currently we output `value`, so for the first we're getting the hash when we want the `value..@value` string. 
A test transform looks like;
```
{"cho_title":{"und-Arab":["عريس الهناء"]},"cho_contributor":{"ar-Arab":["Director: محمود فريد"],"und-Arab":["Actor: محمد عوض"]},"cho_date":{"en":["1974"]},"cho_date_range_norm":[1974],"cho_date_range_hijri":[1393,1394],"cho_dc_rights":{"en":["https://rbsc.princeton.edu/services/imaging-publication-s …
```
> Account for language tagged values in IIIF manifests

- catalogs/harvard.yaml
We need to ensure that ID that is captured is unique (and not a list), so if the XPath returns more than one result, we get a list. This breaks the ability to remove duplicates from the dataframe and thus causes an error when writing the file.
> Use a more granular xpath query for the ID

- catalogs/harvard.yaml
- catalogs/qnl.yaml
- dlme_airflow/utils/qnl.py
- Adds QNL and Harvard IHP
- QNL post harvest task was writing 'nan' strings to csv output. I couldn't figure out how to not do that, so instead I wrote 'NOT PROVIDED' and then remove this value in traject
- Once we have a full harvest of QNL, I will need to revise this to make sure we are getting all role values (this only gets 'author', but I don't know what other roles to look for)
> add qnl and harvard ihp

- dlme_airflow/tasks/transform_validation.py
- tests/tasks/test_transform_validation.py
We original observed a bug when running locally that indicated duplication of records in the ndjson output, however, we are not seeing that bug in the AWS deployment.
> Remove halving of ndjson count bug

- dlme_airflow/drivers/iiif_json.py
- tests/drivers/test_iiif_json.py
You can now configure the IIIF driver to wait between HTTP requests similarly to the OAI driver. If you add `wait: n` where n is an integer, to the collection's `args` section.
Closes #299
> Added wait to the IIIF Driver

- dlme_airflow/harvester/source_harvester.py
- tests/harvester/test_source_harvester.py
We misunderstood the count difference that included the headers because the test case was including the headers while the normal pandas df does not.
This is a small fix for that.
> Fix bug between test arrays and actual csv file row counts

- dlme_airflow/drivers/iiif_json.py
Small bug fix. If the metadata value is an empty string, the check for `dict` fails, and we're likely adding a blank value to the output.
This fixes the error thrown in harvesting if the value is blank.
> Avoid blank metadata error when getting value

- catalogs/qnl.yaml
- dlme_airflow/tasks/transform_validation.py
- tests/tasks/test_eval_record_count_formula.py
This gives us an option to configure a math operation to be performed on the harvested record count. Currently its only needed for QNL, but I can envision other needs. For example, if we harvest all records and then delete some during a legitimate post_harvest task.
Hold for @aaron-collier to review after vacation.
> Make record count formula configurable, fixes #312

- catalogs/sakip_sabanci_museum.yaml
This aligns the expected data_path in dlme-transform with the configured path in airflow.
Locally confirm these now pass transform validation:
> Match Sakip Sabanci data-path to dlme-transform expectation

- dlme_airflow/drivers/oai_xml.py
- tests/drivers/test_oai_xml.py
This rearranges the logic to ensure that we get full tags (i.e. `035_a`) instead of top level (i.e. `035`).
Hold until @jacobthill can test against other OAI collection to ensure this doesn't break non-marc related collections.
> Make sure oai_xml tags include sub field tags

- dlme_airflow/drivers/oai_xml.py
- tests/data/xml/oai-dc.xml
- tests/drivers/test_oai_xml.py
@jacobthill the issue with Texas Tech is that in at least one record they provide an empty publisher element. So we get something like:
```
<dc:publisher>Digitized by the Southwest Collection/Special Collections Library.</dc:publisher>
<dc:publisher/>
```
This PR checks if there are any keys once we flatten the value.
> Avoid blank OAI xml elements

- bin/mapping/data_validation.py
- bin/mapping/get_input_fields.py
- catalogs/princeton.yaml
This removes two collections from Princeton that are also included in the Islamic Manuscripts collection. As I worked through mapping Princeton, I revised the mapping debugging scripts to help spot mapping issues. 
The data_validation script is not perfect but it is not used in production. It is used manually to validate traject mappings. It will continue to improve as I map more collections.
> remove redundant princeton collections, revise mapping scripts

- README.md
- bin/get
- dlme_airflow/drivers/oai_xml.py
- tests/data/xml/record_12345.xml
- tests/drivers/test_oai_xml.py
This adds an option to the command line harvest by ID (using the `GetRecord` OAI method). This could easily be used for a collection configuration if it were a single record as well, but that is unlikely to be useful (and should only require some updated documentation).
Note: This currently only supports OAI collections.
> Add command line option to harvest only a single record by ID for debugging

- docker-compose.prod.yaml
- docker-compose.yaml
Due to a high severity risk, this PR:
- Sets requirepass with a password for redis
- Removes Flower to limit port exposure
The password is stored in vault and set to an ENV var via puppet.
> Security updates for on prem deployment

- docker-compose.prod.yaml
- docker-compose.yaml
This docker proxy is required to allow a DockerOperator based task access to the HOST storage through the docker service as the "docker-in-docker" structure needs this proxy passthrough to make it availble.
> Add docker proxy to allow mount access to docker-in-docker tasks

- .circleci/config.yml
As we're no longer deploying to AWS and instead deploying on prem, remove the aws ecs update from the circle build.
> Remove update-ecs task from circleci build

- tests/utils/test_qnl.py
- tests/utils/test_yale.py
> Mock write to_csv when testing to avoid overwriting fixture data

- dlme_airflow/drivers/iiif_json.py
- tests/drivers/test_iiif_json.py
`_flatten_list()` will ensure that lists that are contained in other lists get flattened for IIIF manifest metadata.
So a list like:
```python
["abc", ["def"], ["ghi", "jkl"]]
```
will get flattened into:
```python
["abc", "def", "ghi", "jkl"]
```
Fixes #338
> Flatten sub-lists

- README.md
- bin/report
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/harvest_report.py
- docker-compose.prod.yaml
- docker-compose.yaml
- tests/conftest.py
- tests/tasks/test_harvest_report.py
This is a small PR that does a couple of things.
- There is a small change to read the `ndjson` (IR: intermediate representation) from the local shared storage instead of fetching it from S3
- This adds a method for calling the report manually from the command line for testing/development.
Note: The codeclimate failure below is an existing complexity warning, this simply changed the name of the method. Refactoring would be for a different ticket, but it's unlikely to improve the complexity of this task at this time.
> Enable on prem report task

- dlme_airflow/utils/dataframe.py
Ensure that the unique id is NOT a list or else it will fail deduplication. Without this all OAI harvests will fail with an error like:
```
TypeError: unhashable type: 'list'
```
Alternatively it might be possible to fix the problem upstream in the
OAI harvesting code that seemed to get broken in 9ef80eea9f87d5dd61f923f73c842936774b4453
> Ensure unique id is not a list

- .gitignore
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/archive.py
- dlme_airflow/utils/dataframe.py
- tests/tasks/test_archive.py
Add an archive task to the end of the ETL pipeline. The task will archive the harvested data to an archive folder within the working directory using a timestamped filename.
If the harvested data is empty (just a CSV header) then the archive is not written. If the harvested data is identical (sha256 hash) of the previous archive it also is not written. This is done to prevent the archive directory from filling up with unnecessary files.
Closes #364
> Archive task

- docker-compose.yaml
This should keep the docker images from automatically starting and not stopping
> Remove restart: always from docker-compose dev

- .gitignore
- dlme_airflow/models/collection.py
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/index.py
- dlme_airflow/tasks/transform_validation.py
- tests/models/test_collection.py
- tests/tasks/test_archive.py
- tests/tasks/test_transform_validation.py
Removes AWS specific code related to transform validation, and compares the length of the DataFrame for the harvested data with the transformed NDJSON data stored in the "metadata" directory.
This is in draft awaiting further information about what type of validation notification is needed. Or alternatively that could be a separate PR. Validation failures will halt workflows, so they should be pretty obvious. The validation task log will have information about why it failed.
Closes #366
> Transform validation

- README.md
Remove AWS mentions from the documentation and move the .env configuration
higher up before docker commands.
> Remove mention of AWS

- docker-compose.prod.yaml
Currently, this path is only available to transform as it is directly mounted through the docker host. We need this mount available within airflow for the validation task.
> Mount the metadata output and archive share for access by airflow

- docker-compose.prod.yaml
- docker-compose.yaml
The local host paths are not available to the docker image here, they need to be the paths on the image.
> Use docker container path for archive path, not host path

- dlme_airflow/drivers/oai_xml.py
This was a temporary encoding used when debugging QNL and not intended to go into main.
> Remove temporary encoding used for QNL

- dlme_airflow/tasks/transform.py
This should ensure that we are always pulling dlme-transform:latest when a transform task is run.
> Set force_pull=True on transform task

- dlme_airflow/drivers/oai_xml.py
- tests/drivers/test_oai_xml.py
Closes #406 
These character encodings where used when debugging QNL data being translated to CSV, since we are now using JSON this debugging in no longer necessary.
> Remove debug character encoding for qnl

- bin/report
- dlme_airflow/task_groups/etl.py
- dlme_airflow/tasks/mapping_report.py
- dlme_airflow/tasks/send_mapping_report.py
- tests/tasks/test_harvest_report.py
The name harvest_report was misleading; its a report on the traject mapping results.
> rename harvest_report to maaping_report

- README.md
- bin/validate-traject
Adds a new utility to check that traject configs map all, and only, intended fields by comparing all fields present in the input data with those mapped in the traject config. Writes a report listing unmapped fields and fields the traject file attempts to map that do not exist in the input data.
Updates the Readme.
> Add new traject config validation utility

- catalogs/ucla.yaml
- dlme_airflow/tasks/post_harvest.py
- dlme_airflow/utils/add_iiif_v3_source.py
- tests/utils/test_add_iiif_v3_source.py
I considered several options for implementing this, particularly using the existing drivers for the second data source. I realized, however, that the only case we have for merging two data sources is when one of them is IIIF v3. It would be great to merge IIIF v2 sources with their OAI-PMH counterparts (we have some cases for that) but the IIIF v2 sources lack the thumbnail key which is needed to merge the two data frames. We've never had another case for merging two data sources. So considering that if we used the `iiif_json` driver, we would need to make the catalog considerable more complex (we would double all of the fields, paths, etc.), we would need to modify the drive to look for different data settings, and we would need to modify the tests, its seemed better to contain this in a …
> add ucla collections and related post harvest task, fixes #427

- docker-compose.prod.yaml
These environment variables need to be explicitly included from the host to the docker containers.
> Add smtp connection to docker-compose-prod

- catalogs/brooklyn.yaml
- catalogs/catalog.yaml
- catalogs/loc.yaml
- catalogs/met.yaml
- dlme_airflow/drivers/json.py
- dlme_airflow/utils/partition_url_builder.py
- tests/data/json/loc.json
- tests/drivers/test_json.py
- tests/support/schemas/schema.yaml
This is a spike on simplifying the complexity of paged JSON content - this should eventually provide a "partition url builder" class so that the majority of the json driver is reusable in order to avoid duplication across vendor specific drivers.
> Refactor paging into PartitionBuilder

- dlme_airflow/utils/read_df.py
- tests/utils/test_read_df.py
When reading JSON data back into Pandas we have to be careful not to let Pandas infer types or else a column named 'date' with a string '1960' in it will get parsed as a datetime, which then causes it to be persisted incorrectly.
I added [a test](https://github.com/sul-dlss/dlme-airflow/blob/41052ecd64a79ed5259f3f5c5f46fb24c9f1729f/tests/utils/test_read_df.py#L16-L23) that initially failed, until I made the correction to how JSON is read in.
Fixes #482
> Prevent pandas data type inference

- Dockerfile.proxy
- docker-compose.prod.yaml
- docker-compose.yaml
I have been unable to start dlme-airflow on my local machine since getting the updated laptop, After some debugging, I discovered that this image we're using to proxy through docker for file system needs no longer works properly as it's 9 years old and it's base image is deprecated.
This removes the dependency on an external image and build a local image based on `bobrik/docker-socat` but uses `alpine:latest`.
> Remove far out of date docker-socat for local build

- README.md
- pyproject.toml
These are a few small changes to our `pyproject.toml` file so that uv is happier about running scripts in the bin subdirectory.
I think going forward we may want to move the utilities into the dlme_airflow module, and then add them to the `pyproject.toml` file as scripts:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts
Fixes #553
> Changes for uv and bin scripts

- dlme_airflow/utils/add_thumbnails.py
- tests/data/csv/penn.csv
- tests/utils/test_add_thumbnails.py
Penn Museum changed the way they share data and the columns available. The url column is no longer available but can be built with the uri so I added that logic to the `get_thumbnail` function and also added some error handling for JSONDecodeErrors since I encountered one during testing.
> adjust Penn thumbnail fetching due to data changes on their end

- dlme_airflow/utils/add_thumbnails.py
- tests/data/csv/penn.csv
- tests/data/json/penn.json
- tests/utils/test_add_thumbnails.py
This never got updated when we moved over to operating on json instead of csv so the thumbnails from the Penn post harvest task didn't show up, fixes https://github.com/sul-dlss/dlme-airflow/issues/568.
> make Penn post harvest operate on json instead of csv

- dlme_airflow/drivers/iiif_json.py
Fixes Leiden harvest for IIIFv2 metadata values that are language tagged within a dict and not a list.
> Ensure metadata values format is retained from provider

- catalogs/newcastle.yaml
- catalogs/shahre_farang.yaml
- dlme_airflow/drivers/xml.py
- tests/data/xml/paged/page_1.xml
- tests/data/xml/paged/page_2.xml
- tests/data/xml/paged/resumption_token_1.xml
- tests/data/xml/paged/resumption_token_2.xml
- tests/drivers/test_xml.py
Fixes #428 
This adds basic paging either by a numeric increment or `resumptionToken` to the custom XML driver.
> Add basic paging to the XML driver

- dlme_airflow/utils/partition_url_builder.py
This is a simple bug that is raised in aub/aladab because it's the only iiif_v3 collection that pages more than a single page of results (16000+).
Fixes #611
> Fix bug with result count accumulating in iiif_v3 pages

- catalogs/catalog.yaml
- catalogs/openn.yaml
- dlme_airflow/drivers/xml.py
- dlme_airflow/utils/partition_url_builder.py
- tests/data/xml/paged/collection.html
- tests/data/xml/paged/record_1.xml
- tests/data/xml/paged/record_2.xml
- tests/drivers/test_xml.py
Fixes #526 
This adds a `link_text` option to the paging config and uses that data to scrape the collection_url for links based on the link_text value and return those URLs are records, then reads each URL into a record for building the dataframe.
> Automate OPenn - scrape HTML for record links

- catalogs/newcastle.yaml
When testing newcastle, it was clear their output format changed recently. This updates the config to match the fields as returned.
> Update newcastle configuration based on provider update

- catalogs/openn.yaml
- dlme_airflow/drivers/xml.py
Fixes OPenn catalog and adjusts xml driver so that the harvest url is available in the xml file. This solves a particular problem with OPenn since we use that url to build the preview and agg_is_shown_at fields but it also will be useful for debugging xpath queries since now we can see missing fields in a harvested record and open the original for comparison.
> harvest openn, closes #648

- config/deploy/dev.rb
This line has been a no-op since dlss-capistrano 5.2.0. Setting up the one-time key is done automatically in dlss-capistrano now.
> Remove explicit one-time key setup
